version: '2'
services:
    elasticsearch:
        image: lbischof/elasticsearch
        user: '1000'
    logstash:
        build: .
        links:
            - elasticsearch
        environment:
            ELASTICSEARCH_SERVICE_HOST: elasticsearch
    kibana:
        image: lbischof/kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        environment:
            ELASTICSEARCH_SERVICE_HOST: elasticsearch
